### ISSUE TITLE
Meybe also Array.prototype.findIndexRight

### ISSUE THREAD

**Issue by Kingwl** [tc39/proposal-array-find-from-last#1]

**Comment by ljharb** [comment]
`.findIndexRight`, for consistency's sake.

**Comment by hax** [comment]
I guess `findLast` and `findLastIndex` would be better name?

**Comment by ljharb** [comment]
Despite `.reduceRight`, trimStart/trimEnd/padStart/padEnd seems to suggest that right/left should be avoided, and there's no precedent for first/last.

**Comment by hax** [comment]
> and there's no precedent for first/last.

@ljharb : `lastIndexOf`

**Comment by ljharb** [comment]
ha, fair enough :-)
