### ISSUE TITLE
Naming concerns: should be `findLast()` or `findFromEnd()`, not `findFromLast()`

### ISSUE THREAD

**Issue by tabatkins** [tc39/proposal-array-find-from-last#13]
"last" refers to a position in an ordered list, "end" refers to a direction; we use these terms consistently in the existing array and string functions.

So if we want to use "last", the function name needs to be referring to an index: `findLast()`. Or we can keep the directional `findFromX()` spelling, but need to switch to a directional word: `findFromEnd()`.

**Comment by bakkot** [comment]
I believe `findLast` and `findLastIndex` are the currently proposed names, per [the readme](https://github.com/tc39-transfer/proposal-array-find-from-last#core-features).

**Comment by tabatkins** [comment]
Ah, indeed. Cool then.

**Comment by Kingwl** [comment]
Yep. 
BTW: That's why the name of proposal is `array-find-from-last` rather than `array-prototype-findlast`.

**Comment by tabatkins** [comment]
That's exactly why I was confused - the name of the repo uses the wrong words. ^_^

**Comment by Kingwl** [comment]
Okay. I'll close the issue. Please feel free to reopen or create another one.
