### ISSUE TITLE
Transfer repo to tc39-transfer

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-array-find-from-last#15]
Congrats on stage 1! Please follow [these instructions](https://github.com/tc39/proposals#onboarding-existing-proposals) (i've invited you to the tc39-transfer org already).

**Comment by Kingwl** [comment]
Thank you very much!

**Comment by Kingwl** [comment]
Hi. I'd like to build a full version of polyfill like es-shims. 

Would you mind tell me what's the best practice?
EG: 
Are there any github-template or cli? or something like that to setup a repo simple & fast.
And should I create a new repo to implement the polyfill? 

Thanks!

**Comment by ljharb** [comment]
The best practices are as follows:
 - do not create a polyfill under the tc39 org - so yes, a new repo and not this one.
 - do not polyfill anything at all before stage 3 - so I’d suggest doing nothing for now.
 - as for a template, i always create one in the es-shims org, and will do so once this proposal reaches stage 3, so while you’re welcome to create one, it’s not strictly necessary :-)

Closing, since the repo is now transferred.

**Comment by Kingwl** [comment]
Thanks for the reply. I'd like to avoid the current polyfill soon.

**Comment by ljharb** [comment]
The main thing is that stage 1 is for investigating a problem space - so there isn't anything *to* polyfill yet. So it doesn't really make sense until at least stage 2, which is where there's a solution shape in mind. There's also a higher risk of creating web compatibility problems before stage 3, which is when the solution design is largely finalized.

**Comment by Kingwl** [comment]
Okay. Got it.
Another problem is how could I(or may I) test the web compatibility？

**Comment by ljharb** [comment]
I'm not aware of any way that can be tested besides actually shipping it in browsers, or asking browsers to ship metrics-gathering that can check it for you. While you're welcome to ask, it's usually a very hard sell - i wasn't able to get the metrics-gathering i wanted for `globalThis`, for example.

**Comment by Kingwl** [comment]
Sad. Anyway Thanks for your help.

**Comment by bakkot** [comment]
For new APIs like this it's usually also worth checking once-popular libraries like Mootools to see if they might collide, although that can't tell you definitively either way whether it will be web-compatible.

**Comment by ljharb** [comment]
That's true; auditing Mootools, Prototype.js, and core-js will cover likely offenders (but as @bakkot says, isn't exhaustive)
