### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Kingwl** [tc39/proposal-array-find-from-last#9]
- findRight
- findIndexRight
- findLast
- findIndexLast
- findEnd
- findIndexEnd

**Comment by Kingwl** [comment]
- ***Right -> `reduce` & `reduceRight`

- ***End-> `trimStart` & `trimEnd`

- ***Last -> `lastIndexOf` but no `xxxLast`

**Comment by ljharb** [comment]
Don't forget `String.prototype.padEnd`, which was added most recently along with `trimEnd`.

**Comment by JeKachan** [comment]
Should be introduced

- includesRight

- someRight

- everyRight

in this case?

**Comment by Kingwl** [comment]
Nope. These method return boolean only. That means we don't really care the order. Well it's may faster.

**Comment by JeKachan** [comment]
I think this matters, from performance perspective, when need check big chunk of data beginning from end

**Comment by bakkot** [comment]
I have a strong preference for `findLast` and `findLastIndex`, to match `lastIndexOf`, which is the closest analogy.

The fact that Lodash and Rambda both use that name suggests other people also find it to be the natural choice. Those are also the names that [previous proposals](https://esdiscuss.org/topic/array-findlast-and-findlastindex) have reached for.

**Comment by Kingwl** [comment]
@bakkot Thanks for the reminding. 

I'm also preference `**Last` too

BTW: Seems the original thread is by @Nokel81 @kdex @ljharb.

**Comment by Kingwl** [comment]
I'd like to rename to `**Last` if there aren't anyone disagree.

**Comment by Nokel81** [comment]
Oh cool, my idea is being taken up again. Yeah, I think **last would be better here. Especially since Right implies left to right but we only really care about first to last.
